### PR TITLE
update readme ( spelling corrections ) 😅

### PR DESCRIPTION
**Pull request by Regedit-msc**
No vex, It was just throwing me off.
Great work, your articles are really insightful .
😅 Forgive me again but I want to bring it to your notice that your hashnode blog doesn't point to your github profile, It instead points tp github pages. 
I'm looking for collaborations on stuff , If you interested hmu😄.

### CODE REVIEW

**Comment by jomefavourite** [comment]
Thank you so much, I can't spell 😂.
I've fixed the link, thanks. 

Sure, I'll love to collaborate

**Comment by Regedit-msc** [comment]
Ok great .I have a repo on my profile called bloggerville if you are chanced, take a look at it I really want to redo the front end to make it a bit nicer . I just bootstrapped the whole thing . [bloggerville](https://bloggerville.herokuapp.com)

**Comment by jomefavourite** [comment]
Okay, I've gone through the site and I'm interested.

 I'll go through the repo now.

**Comment by Regedit-msc** [comment]
Great!

**Comment by Regedit-msc** [comment]
Before cloning the repo let me quickly push updates😅

**Comment by Regedit-msc** [comment]
Or just tell me when you are about to clone the repo so I will push updates

**Comment by jomefavourite** [comment]
But I haven't seen .ejs format before, what framework did you use?

I have no idea about .ejs but I'll love to contribute to the frontend view.

**Comment by Regedit-msc** [comment]
ejs is  a templating engine in node js it won't affect the code in any way. I used it to render the data from the server in front end

**Comment by Regedit-msc** [comment]
All the front end code is shared  within the public and the views folder

**Comment by Regedit-msc** [comment]
The layout  is in the views . The css and js is in the public. The .ejs files are basically html files

**Comment by jomefavourite** [comment]
Okay, but is it that I'll just use plain index.html, sass and JS, then you'll convert it to .ejs?

I'm not yet familiar with backend technologies.

**Comment by Regedit-msc** [comment]
Alright that would be great

**Comment by jomefavourite** [comment]
Could we take the discussion to WhatsApp, I noticed your number is on your repo.

**Comment by Regedit-msc** [comment]
Yes I would love that . Conversing here is weird

**Pull request merged**
